sudo: true
language: node_js
node_js:
  - node
env:
  global:
    - COVERALLS_PARALLEL=true
jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

git:
  quiet: true
cache: npm
script:
  npm test
