sudo: true
language: node_js
node_js:
  - node
env:
  global:
    - COVERALLS_PARALLEL=true
jobs:
notifications:
  webhooks: https://coveralls.io/webhook
git:
  quiet: true
cache: npm
script:
  npm test
